# Regenerates ansi.css, the colour classes cli::ansi_html() emits. The docs'
# output blocks have a light background, so the 16 base colours are replaced
# with a palette that stays readable on it (cli's default is meant for dark
# terminals: its yellow and white vanish on white). The 256-colour cube
# (indices 16-255) keeps cli's values.
#
#   Rscript site/make-ansi-css.R site/ansi.css

base <- c(
  "#24292f", "#cf222e", "#1a7f37", "#9a6700", "#0969da", "#8250df", "#1b7c83", "#6e7781",
  "#57606a", "#a40e26", "#116329", "#7d4e00", "#0550ae", "#6639ba", "#136f7a", "#8c959f"
)

x <- cli::ansi_html_style()
nm <- names(x)
val <- unlist(x)
is_base <- grepl("^\\.ansi-(bg-)?color-([0-9]|1[0-5])$", nm)
keep <- grepl("^\\.ansi-(bold|italic|underline|crossedout|(bg-)?color-[0-9]+)$", nm) & !is_base

writeLines(
  c(
    "/* Generated by make-ansi-css.R -- edit that, not this. */",
    paste0(".ansi-color-", 0:15, " { color: ", base, " }"),
    paste0(".ansi-bg-color-", 0:15, " { background-color: ", base, " }"),
    paste(nm[keep], val[keep])
  ),
  commandArgs(TRUE)[1]
)
