test_that("dbdt_profile() summarises every column in the database", {
  aq <- data.table::as.data.table(datasets::airquality)
  d <- as.dbdt(aq, name = "aq_profile")
  p <- dbdt_profile(d)
  expect_s3_class(p, "data.table")
  expect_identical(p$col, names(aq))
  expect_equal(attr(p, "n_rows"), nrow(aq))
  expect_equal(p$n_na, vapply(aq, function(v) sum(is.na(v)), numeric(1)), ignore_attr = TRUE)
  expect_equal(p$pct_na, p$n_na / nrow(aq))
  expect_equal(p$n_distinct, vapply(aq, data.table::uniqueN, numeric(1), na.rm = TRUE), ignore_attr = TRUE)
  expect_equal(as.numeric(p$min), vapply(aq, min, numeric(1), na.rm = TRUE), ignore_attr = TRUE)
  expect_equal(as.numeric(p$max), vapply(aq, max, numeric(1), na.rm = TRUE), ignore_attr = TRUE)
})

test_that("dbdt_profile() handles a column subset, distinct = FALSE and binary columns", {
  con <- DBI::dbConnect(duckdb::duckdb())
  on.exit(DBI::dbDisconnect(con, shutdown = TRUE))
  DBI::dbExecute(con, "CREATE TABLE b (id INTEGER, payload BLOB, d DATE)")
  DBI::dbExecute(con, "INSERT INTO b VALUES (1, 'abc'::BLOB, DATE '2024-01-02'), (2, NULL, NULL)")
  p <- dbdt_profile(dbdt(con, "b"), distinct = FALSE)
  expect_true(all(is.na(p$n_distinct)))
  expect_equal(p[col == "payload"]$n_na, 1)
  expect_true(is.na(p[col == "payload"]$min))
  expect_equal(p[col == "d"]$min, "2024-01-02")
  expect_identical(dbdt_profile(dbdt(con, "b"), cols = "id")$col, "id")
  expect_error(dbdt_profile(dbdt(con, "b"), cols = "nope"), "no column")
})
